- run: ls

      # prevents fatal: detected dubious ownership in repository at '/__w/github-automation/github-automation'
      - run: git config --global --add safe.directory /__w/github-automation/github-automation
      - run: git config --global --add safe.directory /__w/DenverFire/github-automation

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
